---
- name: Pull docker image of calculator mini project
  hosts: all
  tasks:
    - name: Pull calculator devops image
      docker_image:
        name: vaibhavi1998/calculator-spe
        source: pull